baseURL = "https://rubenaleman.de/"
languageCode = "en-us"
title = "Home"
disableKinds = ["taxonomy", "term", "RSS"]
theme = "hugo-coder"
enableRobotsTXT = true

[params]
gravatar = "ruben.aleman@makandra.de"
author = "Ruben Aleman"
info = "DevOps Engineer @STACKIT"
description = "Ruben Aleman's website"
keywords = "developer,devops,operations"
colorScheme = "dark"


[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 1
url = "https://gitlab.com/ruben.aleman"
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 3
url = "https://github.com/What-is-water93"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/ruben-aleman-4930642aa/"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-xing fa-2x"
weight = 4
url = "https://www.xing.com/profile/Ruben_Aleman"
[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"
